export const SHOW_MODAL = 'SHOW_MODAL';

export const GET_EMPLOYEES = 'GET_EMPLOYEES';
export const EMPLOYEES_RECEIVED = 'EMPLOYEES_RECEIVED';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const EMPLOYEE_UPDATED = 'EMPLOYEE_UPDATED';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EMPLOYEE_ADDED = 'EMPLOYEE_ADDED';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const EMPLOYEE_DELETED = 'EMPLOYEE_DELETED';

export const GET_PAYMENTS = 'GET_PAYMENTS';
export const PAYMENTS_RECEIVED = 'PAYMENTS_RECEIVED';

export const GET_CITIES = 'GET_CITIES';
export const CITIES_RECEIVED = 'CITIES_RECEIVED';

export const GET_DISTRICTS = 'GET_DISTRICTS';
export const DISTRICTS_RECEIVED = 'DISTRICTS_RECEIVED';

export const GET_WARDS = 'GET_WARDS';
export const WARDS_RECEIVED = 'WARDS_RECEIVED';

export const GET_EMPROLES = 'GET_EMPROLES';
export const EMPROLES_RECEIVED = 'EMPROLES_RECEIVED';
export const UPDATE_EMPROLE = 'UPDATE_EMPROLE';
export const EMPROLE_UPDATED = 'EMPROLE_UPDATED';
export const ADD_EMPROLE = 'ADD_EMPROLE';
export const EMPROLE_ADDED = 'EMPROLE_ADDED';
export const DELETE_EMPROLE = 'DELETE_EMPROLE';
export const EMPROLE_DELETED = 'EMPROLE_DELETED';

export const GET_ORDERS = 'GET_ORDERS';
export const ORDERS_RECEIVED = 'ORDERS_RECEIVED';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const ORDER_UPDATED = 'ORDER_UPDATED';
export const ADD_ORDER = 'ADD_ORDER';
export const ORDER_ADDED = 'ORDER_ADDED';
export const DELETE_ORDER = 'DELETE_ORDER';
export const ORDER_DELETED = 'ORDER_DELETED';

export const GET_SHOPS = 'GET_SHOPS';
export const SHOPS_RECEIVED = 'SHOPS_RECEIVED';
export const UPDATE_SHOP = 'UPDATE_SHOP';
export const SHOP_UPDATED = 'SHOP_UPDATED';
export const ADD_SHOP = 'ADD_SHOP';
export const SHOP_ADDED = 'SHOP_ADDED';
export const DELETE_SHOP = 'DELETE_SHOP';
export const SHOP_DELETED = 'SHOP_DELETED';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_AUTH_ERROR = 'USER_AUTH_ERROR';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_UPDATE_AUTH = 'USER_UPDATE_AUTH';
export const USER_UPDATE_AUTH_SUCCESS = 'USER_UPDATE_AUTH_SUCCESS';
export const GET_USERS = 'GET_USERS';
export const USERS_RECEIVED = 'USERS_RECEIVED';
export const ADD_USER = 'ADD_USER';
export const USER_ADDED = 'USER_ADDED';
export const DELETE_USER = 'DELETE_USER';
export const USER_DELETED = 'USER_DELETED';
export const UPDATE_USER = 'UPDATE_USER';
export const USER_UPDATED = 'USER_UPDATED';
export const GET_USER = 'GET_USER';
export const GET_USER_BY_ID = 'GET_USER_BY_ID';
export const USER_RECEIVED = 'USER_RECEIVED';

export const EMPLOYEE_LOADING = 'EMPLOYEE_LOADING';
export const EMPLOYEE_LOADED = 'EMPLOYEE_LOADED';
export const EMPLOYEE_LOGIN = 'EMPLOYEE_LOGIN';
export const EMPLOYEE_LOGOUT = 'EMPLOYEE_LOGOUT';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_AUTH_SUCCESS = 'UPDATE_AUTH_SUCCESS';

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const ERRORS_CLEARED = 'ERRORS_CLEARED';
export const ERRORS_RETURNED = 'ERRORS_RETURNED';

export const GET_HISTORY = 'GET_HISTORY';
export const PUSH_HISTORY = 'PUSH_HISTORY';
export const LOAD_HISTORY = 'LOAD_HISTORY';

export const GET_VARIANTVALS = 'GET_VARIANTVALS';
export const ADD_VARIANTVAL = 'ADD_VARIANTVAL';
export const VARIANTVALS_RECEIVED = 'VARIANTVALS_RECEIVED';
export const VARIANTVAL_ADDED = 'VARIANTVAL_ADDED';
export const DELETE_VARIANTVAL = 'DELETE_VARIANTVAL';
export const VARIANTVAL_DELETED = 'VARIANTVAL_DELETED';
export const UPDATE_VARIANTVAL = 'UPDATE_VARIANTVAL';
export const VARIANTVAL_UPDATED = 'VARIANTVAL_UPDATED';

export const GET_ROLES = 'GET_ROLES';
export const ROLES_RECEIVED = 'ROLES_RECEIVED';
export const ADD_ROLE = 'ADD_ROLE';
export const ROLES_ADDED = 'ROLES_ADDED';
export const DELETE_ROLE = 'DELETE_ROLE';
export const ROLE_DELETED = 'ROLE_DELETED';
export const UPDATE_ROLE = 'UPDATE_ROLE';
export const ROLE_UPDATED = 'ROLE_UPDATED';

export const GET_PAYSLIPS = 'GET_PAYSLIPS';
export const ADD_PAYSLIP = 'ADD_PAYSLIP';
export const DELETE_PAYSLIP = 'DELETE_PAYSLIP';
export const GET_PAYSLIP = 'GET_PAYSLIP';
export const PAYSLIPS_LOADING = 'PAYSLIPS_LOADING';

export const GET_MEMBERS = 'GET_MEMBERS';
export const ADD_MEMBER = 'ADD_MEMBER';
export const GET_MEMBER = 'GET_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';

export const GET_SEARCH_MEMBERS = 'GET_SEARCH_MEMBERS';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_BY_MOVIECAT = 'GET_PRODUCTS_BY_MOVIECAT';
export const PRODUCTS_RECEIVED = 'PRODUCTS_RECEIVED';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_ADDED = 'PRODUCT_ADDED';
export const GET_PRODUCT = 'GET_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const PRODUCT_UPDATED = 'PRODUCT_UPDATED';
export const UPDATE_PRODUCTADD = 'UPDATE_PRODUCTADD';
export const PRODUCTADD_UPDATED = 'PRODUCTADD_UPDATED';

export const GET_ADDRESSES = 'GET_ADDRESSES';
export const ADDRESSES_RECEIVED = 'ADDRESSES_RECEIVED';
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADDRESS_ADDED = 'ADDRESS_ADDED';
export const GET_ADDRESS = 'GET_ADDRESS';
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const ADDRESS_DELETED = 'ADDRESS_DELETED';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const ADDRESS_UPDATED = 'ADDRESS_UPDATED';

export const GET_PRODUCTVARS = 'GET_PRODUCTVARS';
export const GET_PRODUCTVARS_BY_IDSHOP = 'GET_PRODUCTVARS_BY_IDSHOP';
export const PRODUCTVARS_RECEIVED = 'PRODUCTVARS_RECEIVED';
export const ADD_PRODUCTVAR = 'ADD_PRODUCTVAR';
export const PRODUCTVAR_ADDED = 'PRODUCTVAR_ADDED';
export const GET_PRODUCTVAR = 'GET_PRODUCTVAR';
export const DELETE_PRODUCTVAR = 'DELETE_PRODUCTVAR';
export const PRODUCTVAR_DELETED = 'PRODUCTVAR_DELETED';
export const UPDATE_PRODUCTVAR = 'UPDATE_PRODUCTVAR';
export const UPDATE_PRODUCTVAR_STATUS = 'UPDATE_PRODUCTVAR_STATUS';
export const PRODUCTVAR_UPDATED = 'PRODUCTVAR_UPDATED';
export const GET_PRODUCTVAR_BY_ID = 'GET_PRODUCTVAR_BY_ID';
export const PRODUCTVAR_RECEIVED = 'PRODUCTVAR_RECEIVED';

export const GET_PRODUCT_CATES = 'GET_PRODUCT_CATES';
export const PRODUCT_CATES_RECEIVED = 'PRODUCT_CATES_RECEIVED';
export const UPDATE_PRODUCT_CATE = 'UPDATE_PRODUCT_CATE';
export const PRODUCT_CATE_UPDATED = 'PRODUCT_CATE_UPDATED';
export const ADD_PRODUCT_CATE = 'ADD_PRODUCT_CATE';
export const PRODUCT_CATE_ADDED = 'PRODUCT_CATE_ADDED';
export const DELETE_PRODUCT_CATE = 'DELETE_PRODUCT_CATE';
export const PRODUCT_CATE_DELETED = 'PRODUCT_CATE_DELETED';

export const GET_MOVIES = 'GET_MOVIES';
export const MOVIES_RECEIVED = 'MOVIES_RECEIVED';
export const UPDATE_MOVIE = 'UPDATE_MOVIE';
export const MOVIE_UPDATED = 'MOVIE_UPDATED';
export const ADD_MOVIE = 'ADD_MOVIE';
export const MOVIE_ADDED = 'MOVIE_ADDED';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const MOVIE_DELETED = 'MOVIE_DELETED';

export const GET_MOVIE_CATES = 'GET_MOVIE_CATES';
export const MOVIE_CATES_RECEIVED = 'MOVIE_CATES_RECEIVED';
export const UPDATE_MOVIE_CATE = 'UPDATE_MOVIE_CATE';
export const MOVIE_CATE_UPDATED = 'MOVIE_CATE_UPDATED';
export const ADD_MOVIE_CATE = 'ADD_MOVIE_CATE';
export const MOVIE_CATE_ADDED = 'MOVIE_CATE_ADDED';
export const DELETE_MOVIE_CATE = 'DELETE_MOVIE_CATE';
export const MOVIE_CATE_DELETED = 'MOVIE_CATE_DELETED';

export const GET_CARTS_BY_IDUSER = 'GET_CARTS_BY_IDUSER';
export const ADD_CART = 'ADD_CART';
export const DELETE_CART = 'DELETE_CART';
export const UPDATE_CART = 'UPDATE_CART';
export const CART_DELETED = 'CART_DELETED';
export const CARTS_RECEIVED = 'CARTS_RECEIVED';
export const CART_ADDED = 'CART_ADDED';
export const CART_UPDATED = 'CART_UPDATED';

export const GET_INVOICES = 'GET_INVOICES';
export const GET_ALL_INVOICES = 'GET_ALL_INVOICES';
export const GET_INVOICE = 'GET_INVOICE';
export const INVOICES_RECEIVED = 'INVOICES_RECEIVED';
export const ADD_INVOICE = 'ADD_INVOICE';
export const INVOICES_ADDED = 'INVOICES_ADDED';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const INVOICE_DELETED = 'INVOICE_DELETED';
export const UPDATE_INVOICE = 'UPDATE_INVOICE';
export const INVOICE_UPDATED = 'INVOICE_UPDATED';
export const INVOICES_LOADING = 'INVOICES_LOADING';

export const GET_INVOICEDETS = 'GET_INVOICEDETS';
export const ADD_INVOICEDET = 'ADD_INVOICEDET';
export const GET_ALL_INVOICEDETS = 'GET_ALL_INVOICEDETS';
export const INVOICEDETS_LOADING = 'INVOICEDETS_LOADING';

export const SHOW_NOTI = 'SHOW_NOTI';

export const ADD_REDUCER = 'ADD_REDUCER';
export const GET_SUPPLIERS = 'GET_SUPPLIERS';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';
export const DELETE_SUPPLIER = 'DELETE_SUPPLIER';
export const GET_SUPPLIER = 'GET_SUPPPLIER';

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER';

export const GET_MATERIALS = 'GET_MATERIALS';
export const ADD_MATERIAL = 'ADD_MATERIAL';
export const DELETE_MATERIAL = 'DELETE_MATERIAL';
export const MATERIALS_LOADING = 'MATERIALS_LOADING';

export const CHECK_CUR_PASS_USER = 'CHECK_CUR_PASS_USER';
export const GET_ALL_MATERIALS = ' GET_ALL_MATERIALS';
export const UPDATE_MATERIAL = 'UPDATE_MATERIAL';
export const UPDATE_QTY_MATERIAL = 'UPDATE_QTY_MATERIAL';

export const GET_REPORTS = 'GET_REPORTS';
export const ADD_REPORT = 'ADD_REPORT';
export const GET_REPORT = 'GET_REPORT';
export const DELETE_REPORT = 'DELETE_REPORT';
export const GET_SEARCH_REPORTS = 'GET_SEARCH_REPORTS';
