version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_HOST= http://localhost:5001
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
