version: "3"
services:
  frontend:
    container_name: frontend
    image: nghthanhtam/fe:latest
    build:
      context: .
      #dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_EMPLOYEE=http://localhost:5001
        - REACT_APP_BACKEND_ADMIN=http://localhost:5002
        - REACT_APP_BACKEND_PRODUCT=http://localhost:5008
        - REACT_APP_BACKEND_USER=http://localhost:5003
        - REACT_APP_BACKEND_ORDER=http://localhost:5004
        - REACT_APP_BACKEND_RATING=http://localhost:5005
        - REACT_APP_BACKEND_LOGGING=http://localhost:5007
        - REACT_APP_BACKEND_PROMOTION=http://localhost:5006
    ports:
      - "3000:80"
    volumes:
      - ./:/frontend
      - /frontend/node_modules
