export const GET_CATEGORIES = "GET_CATEGORIES";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const CATEGORIES_ADDED_FAILED = "CATEGORIES_ADDED_FAILED";
export const CATEGORIES_ADDED = "CATEGORIES_ADDED";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const CATEGORIES_RECEIVED = "CATEGORIES_RECEIVED";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const ERRORS_CLEARED = "ERRORS_CLEARED";
export const ERRORS_RETURNED = "ERRORS_RETURNED";

export const GET_HISTORY = "GET_HISTORY";
export const PUSH_HISTORY = "PUSH_HISTORY";
export const LOAD_HISTORY = "LOAD_HISTORY";

export const GET_ROLES = "GET_ROLES";
export const ADD_ROLE = "ADD_ROLE";
export const DELETE_ROLE = "DELETE_ROLE";
export const UPDATE_ROLE = "UPDATE_ROLE";
export const GET_PAYSLIPS = "GET_PAYSLIPS";
export const ADD_PAYSLIP = "ADD_PAYSLIP";
export const DELETE_PAYSLIP = "DELETE_PAYSLIP";
export const GET_PAYSLIP = "GET_PAYSLIP";
export const PAYSLIPS_LOADING = "PAYSLIPS_LOADING";

export const GET_MEMBERS = "GET_MEMBERS";
export const ADD_MEMBER = "ADD_MEMBER";
export const GET_MEMBER = "GET_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";

export const GET_SEARCH_MEMBERS = "GET_SEARCH_MEMBERS";
export const UPDATE_MEMBER = "UPDATE_MEMBER";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_INVOICES = "GET_INVOICES";
export const ADD_INVOICE = "ADD_INVOICE";
export const GET_INVOICE = "GET_INVOICE";
export const GET_ALL_INVOICES = "GET_ALL_INVOICES";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const INVOICES_LOADING = "INVOICES_LOADING";

export const GET_INVOICEDETS = "GET_INVOICEDETS";
export const ADD_INVOICEDET = "ADD_INVOICEDET";
export const GET_ALL_INVOICEDETS = "GET_ALL_INVOICEDETS";
export const INVOICEDETS_LOADING = "INVOICEDETS_LOADING";

export const SHOW_NOTI = "SHOW_NOTI";

export const ADD_REDUCER = "ADD_REDUCER";
export const GET_SUPPLIERS = "GET_SUPPLIERS";
export const ADD_SUPPLIER = "ADD_SUPPLIER";
export const DELETE_SUPPLIER = "DELETE_SUPPLIER";
export const GET_SUPPLIER = "GET_SUPPPLIER";

export const UPDATE_SUPPLIER = "UPDATE_SUPPLIER";

export const GET_USERS = "GET_USERS";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const GET_USER = "GET_USER";

export const GET_MATERIALS = "GET_MATERIALS";
export const ADD_MATERIAL = "ADD_MATERIAL";
export const DELETE_MATERIAL = "DELETE_MATERIAL";
export const MATERIALS_LOADING = "MATERIALS_LOADING";

export const CHECK_CUR_PASS_USER = "CHECK_CUR_PASS_USER";
export const GET_ALL_MATERIALS = " GET_ALL_MATERIALS";
export const UPDATE_MATERIAL = "UPDATE_MATERIAL";
export const UPDATE_QTY_MATERIAL = "UPDATE_QTY_MATERIAL";

export const GET_REPORTS = "GET_REPORTS";
export const ADD_REPORT = "ADD_REPORT";
export const GET_REPORT = "GET_REPORT";
export const DELETE_REPORT = "DELETE_REPORT";
export const GET_SEARCH_REPORTS = "GET_SEARCH_REPORTS";
